# Generated by Django 6.1 on 2026-08-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.IntegerField(default=85)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Under Review', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
